### ISSUE TITLE
What does the label "relation" mean in the dataset?

### ISSUE THREAD

**Issue by evelynxyx** [aitor-garcia-p/hate-speech-dataset#4]
Could I simply ignore it? Casue the number of texts labeled by it is very small.

**Comment by aitor-garcia-p** [comment]
Hi there,

The meaning of the "relation" tag is explained in the paper (the link is in the readme, but I put it here too: https://aclanthology.org/W18-51.pdf , section 3.2.3 of the paper, page 14)

In few words, a sentence labelled as "relation" needs to be read together with other sentences in the surroundings (the previous and/or next sentence) to understand if it conveys hate-speech or not.
This was added during the labelling campaign to deal with those special cases, but since there are so few, you can simply ignore them. Or you can treat the consecutive sentences with labelled with relation as a single instance with label "hate".
The paper contains a better explanation with a clear example.

Kind regards.

**Comment by evelynxyx** [comment]
Thank you for your detailed answer！
